spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/today_flower?serverTimezone=UTC&useSSL=false
    username: root
    password: rhfelfkrtm!23

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    defer-datasource-initialization: false
    show-sql: true

#  sql:
#    init:
#      mode: always