# 농촌진흥청 국립원예특장과학원 오늘의 꽃 조회 서비스(2.0)
api-encoding-key: SxiFBkwFdvX0KlFjfLEWi6HYwn67iYE40MaNnxIA58ZigkRDrLljf1XLGnQb0Hh01BFX2kaw7PMJCvLlazNFBA%3D%3D
api-decoding-key: SxiFBkwFdvX0KlFjfLEWi6HYwn67iYE40MaNnxIA58ZigkRDrLljf1XLGnQb0Hh01BFX2kaw7PMJCvLlazNFBA==

